class ValidationTextData:
    #  Login
    LOGOUT_BUTTON = "Wyloguj"
    LOGIN_BUTTON = "Zaloguj"
    MY_CHILDREN_LINK_TEXT = "Moje dzieci"
    LOGIN_INFORMATION_IN_DROPDOWN = "Jesteś zalogowana/y jako"
    LOGIN_ENDPOINT = "/klub/zaloguj-sie"
    LOGIN_ENDPOINT_DOCTOR_PAGE = "/logowanie"
    AFTER_LOGIN_ENDPOINT = "/klub-logged-in/moj-klub-maluszka"
    AFTER_LOGIN_ENDPOINT_DOCTOR_PAGE = "/profil"
    INPUT_TAG = "input"
    VALIDATION_ENDPOINT = "/walidacja"
    CAPTCHA = "reCAPTCHA"
    MY_PROFILE_LINK_TEXT = "Mój profil"
    DOCTOR_PAGE = "dlalekarzy"

    # ADD BABY
    ADD_BABY_ENDPOINT = "profil-uzytkownika/dodaj-dziecko"
    CHILDREN_LIST_ENDPOINT = "profil-uzytkownika/lista-dzieci"
    MY_BABY_CLUB_ENDPOINT = "klub-maluszka/moj-klub-maluszka"
    ALERT_COLOR = "#ff0000"
    REQUIRED_FIELD = "Pole jest wymagane"
    I_ACCEPT = "Wyrażam zgodę na:"
    CORRECT_ADDED_BABY_ALERT = "Prawidłowo dodano nowe dziecko"
    IMG_STORK = 'img alt="Ciąża"'
    NO_NAME = "Imię nieznane"
    CONFIRM_BABY_BORN_DATE = "Potwierdź datę urodzenia dziecka"
    NO_GENDER = "Płeć: Nieznana"
    FEMALE_GENDER = "Płeć: Dziewczynka"
    MALE_GENDER = "Płeć: Chłopiec"
    NO_BORN_GIFT = "Paczka Narodziny: NIE"
    BORN_GIFT_YES = "Paczka Narodziny: TAK"
